chore(ci): Update workflows to newer versions from upstream
Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

diff --git a/.github/workflows/node.yml b/.github/workflows/node.yml
--- a/.github/workflows/node.yml
+++ b/.github/workflows/node.yml
@@ -2,11 +2,8 @@
 #
 # https://github.com/nextcloud/.github
 # https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
-#
-# Use lint-eslint together with lint-eslint-when-unrelated to make eslint a required check for GitHub actions
-# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
 
-name: Lint eslint
+name: Node
 
 on: pull_request
 
@@ -14,7 +11,7 @@ permissions:
   contents: read
 
 concurrency:
-  group: lint-eslint-${{ github.head_ref || github.run_id }}
+  group: node-${{ github.head_ref || github.run_id }}
   cancel-in-progress: true
 
 jobs:
@@ -37,20 +34,17 @@ jobs:
               - 'package.json'
               - 'package-lock.json'
               - 'tsconfig.json'
-              - '.eslintrc.*'
-              - '.eslintignore'
               - '**.js'
               - '**.ts'
               - '**.vue'
 
-  lint:
+  build:
     runs-on: ubuntu-latest
 
     needs: changes
     if: needs.changes.outputs.src != 'false'
 
-    name: NPM lint
-
+    name: NPM build
     steps:
       - name: Checkout
         uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
@@ -70,26 +64,36 @@ jobs:
       - name: Set up npm ${{ steps.versions.outputs.npmVersion }}
         run: npm i -g npm@"${{ steps.versions.outputs.npmVersion }}"
 
-      - name: Install dependencies
+      - name: Install dependencies & build
         env:
           CYPRESS_INSTALL_BINARY: 0
           PUPPETEER_SKIP_DOWNLOAD: true
-        run: npm ci
+        run: |
+          npm ci
+          npm run build --if-present
 
-      - name: Lint
-        run: npm run lint
+      - name: Check webpack build changes
+        run: |
+          bash -c "[[ ! \"`git status --porcelain `\" ]] || (echo 'Please recompile and commit the assets, see the section \"Show changes on failure\" for details' && exit 1)"
+
+      - name: Show changes on failure
+        if: failure()
+        run: |
+          git status
+          git --no-pager diff
+          exit 1 # make it red to grab attention
 
   summary:
     permissions:
       contents: none
     runs-on: ubuntu-latest-low
-    needs: [changes, lint]
+    needs: [changes, build]
 
     if: always()
 
     # This is the summary, we just avoid to rename it so that branch protection rules still match
-    name: eslint
+    name: node
 
     steps:
       - name: Summary status
-        run: if ${{ needs.changes.outputs.src != 'false' && needs.lint.result != 'success' }}; then exit 1; fi
+        run: if ${{ needs.changes.outputs.src != 'false' && needs.build.result != 'success' }}; then exit 1; fi
